### ISSUE TITLE
User can login

### ISSUE THREAD

**Issue by lauragracem** [lauragracem/ajax-project#1]
## ⚙️ Feature

Users can login to record and view habits.

## 📐 Functionality

Tracks users' habits to help users build better habits one day at a time.

## 🖼️ Wireframes

![Home (2)](https://user-images.githubusercontent.com/60913524/174879522-b343cd5a-60cc-41bf-bebc-4149768d229c.png)

![HomePage (2)](https://user-images.githubusercontent.com/60913524/174880006-24841a44-343d-469b-b645-59b6d9672141.png)

## ✅ Task List
- [x] Add a 'div [data-view="user-login"]' to the HTML.
- [x] Add a form for creating a username to the 'div [data-view="user-login"]'.
- [x] Make username input 'required'.
- [x] Listen for 'submit' event on 'log in' form.
- [x] Make sure the background behind the linear gradient is white.
- [x] Add 'login as guest' link.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
