### ISSUE TITLE
User can add a habit

### ISSUE THREAD

**Issue by lauragracem** [lauragracem/ajax-project#2]
## ⚙️ Feature

User can input habit(s).

## 📐 Functionality

Habit(s) will be displayed in chronological order as user add them.

## 🖼️ Wireframes
![Add Habit (3)](https://user-images.githubusercontent.com/60913524/174916721-472b62b3-eabb-404f-b36a-93af829b134c.png)
![Add Habit (2)](https://user-images.githubusercontent.com/60913524/174916724-969ddad3-1e6f-49da-aec8-4c2e0ac3a5d8.png)

## ✅ Task List
- [x] Add a 'div[data-vew="habit-form"]' to the HTML.
- [x] Add a form for creating and submitting a habit to the div[data-vew="habit-form"]'.
- [x] Make inputs 'required'. 
- [x] Listen for 'input' event on 'Enter Habit'.
- [x] Listen for 'submit' event on 'habit-form'.
- [x] Create a function to 'POST' habit graph. This creates the habit graph to 'GET' later.
- [x] Create a function to 'GET' habit graph and render graph image on page.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
