### ISSUE TITLE
User can edit and delete habit

### ISSUE THREAD

**Issue by lauragracem** [lauragracem/ajax-project#3]
## ⚙️ Feature

Add an edit icon to edit habit(s) and record time spent working on habit(s).

## 📐 Functionality

User will be able to edit habit(s).

## 🖼️ Wireframes
![Edit Habit (3)](https://user-images.githubusercontent.com/60913524/175408343-e43ab703-2c88-457e-8055-850ce4b2ddd1.png)
![Edit Habit (2)](https://user-images.githubusercontent.com/60913524/175408382-e58a9ec0-4de4-4800-bfd9-f78b874aff3d.png)

## ✅ Task List
- [x] Add an edit icon to edit 'habit'.
- [x] Listen for 'click' event on edit icon.
- [ ] Add delete icon.
- [ ] Listen for 'click' event on delete icon.
- [ ] Use event delegation fro edit and delete icon.
- [ ] Re-render remaining habits after every delete.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
