### ISSUE TITLE
User can add minutes

### ISSUE THREAD

**Issue by lauragracem** [lauragracem/ajax-project#4]
## ⚙️ Feature

Recording the amount of time a user works on their habit(s) is a way to help build discipline. 
The user can start with 10 minutes and work their way up to half an hour, depending on the habit(s).

## 📐 Functionality

User can add, in minutes, how long they worked on their habit(s).

## 🖼️ Wireframes
![Add Minutes (1)](https://user-images.githubusercontent.com/60913524/174135103-e60a4e73-11d6-452c-b846-a43fdf7bdeeb.png)
![Add Minutes](https://user-images.githubusercontent.com/60913524/174135110-15ce0bc4-7215-4a63-84b8-8ffeff91d57e.png)

## ✅ Task List

- [ ] Listen to 'input' events for editing habit and 'enter minutes'.
- [ ] Listen for 'click' event for 'submit' button.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
