### ISSUE TITLE
User can delete habit

### ISSUE THREAD

**Issue by lauragracem** [lauragracem/ajax-project#5]
## ⚙️ Feature

Delete habits when goals are met.

## 📐 Functionality

User can delete habit entries.

## 🖼️ Wireframes
![Delete Habit (1)](https://user-images.githubusercontent.com/60913524/174136913-2a110b22-a21b-4191-b31c-d4297c1e78db.png)
![Delete Habit](https://user-images.githubusercontent.com/60913524/174136928-c356dde9-065d-463a-a8d5-e64302c1640e.png)

## ✅ Task List

- [ ] Add a 'delete' button.
- [ ] Listen to 'click' event for 'delete' button.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
